ecosystem_name: Paramo
country_name: Colombia
authors:
- John Smith
- Jane Smith
biome: TODO
functional_group: N/A
global_classification: Paramo
index: 63
iucn_status: TODO
description: TODO
distribution: TODO
characteristic_native_biota: TODO
abiotic_environment: TODO
key_processes_and_interactions: TODO
major_threats: TODO
ecosystem_collapse_definition: TODO
assessment_summary: TODO
criteria_status:
  A:
    A1: NE
    A2a: NE
    A2b: NE
    A3: NE
  B:
    B1: LC
    B2: LC
    subcriteria: NE
    B3: NE
  C:
    C1: NE
    C2a: NE
    C2b: NE
    C3: NE
  D:
    D1: NE
    D2a: NE
    D2b: NE
    D3: NE
  E:
    E: NE
assessment_outcome: TODO
year_published: TODO
date_assessed: TODO
assessment_credits:
  assessed_by: TODO
  reviewed_by: TODO
  contributions_by: TODO
criterion_a_description: TODO
criterion_b_description: TODO
criterion_c_description: TODO
criterion_d_description: TODO
criterion_e_description: TODO
